### ISSUE TITLE
Twitter-Cards einbauen

### ISSUE THREAD

**Issue by valioDOTch** [mritzmann/NDG-Lieblingswebsite#10]
Um die Shareability für Twitter zu erhöhen sollten Twitter-Cards eingebaut werden.
Beiträge mit Bildern erhalten mehr Aufmerksamkeit.
Ggf. könnte man dies auch mit #3 verknüpfen: für die Generierung des Preview-Bildes wird das Preview der getesteten Website verwendet in Kombination mit automatisch hinzugefügten, zusätzlichen Grafikelementen (Ampelsystem, Überwachungskamera-Symbol, etc.)

einfaches Beispiel zum Einbau von Twitter Cards
https://github.com/linuxmint/linuxmint.github.io/pull/6

Zum Testen
https://cards-dev.twitter.com/validator

**Comment by mritzmann** [comment]
Twitter-Cards befindet sich in der momentanen Version bereits in Verwendung. Siehe:

```
<!-- Twitter Card -->
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@ueberwacht_ch" />
<meta name="twitter:title" content="Wirst Du überwacht?" /
<meta name="twitter:description" content="Wirst du beim Besuch deiner Lieblingswebsite überwacht? Hiermit findest du es heraus." />
<meta name="twitter:image" content="https://ueberwacht.ch/img/twitter_image.jpg" />
```

Die Idee mit einem Preview-Bild der getesteten Webseite finde ich gut. Wäre aber auch nur in Kombination mit #3 möglich.

Freiwillige vor ;-)

**Comment by mritzmann** [comment]
Da die Abstimmung über das NDG nicht mehr aktuell ist, schließe ich hiermit alle Issues. Bei bedarf einer Weiterentwicklung kann dieses Issues erneut geöffnet werden.
