### ISSUE TITLE
OpenGraph einbauen

### ISSUE THREAD

**Issue by valioDOTch** [mritzmann/NDG-Lieblingswebsite#11]
Analog zu #10, jedoch mit OpenGraph-Tags (relevant für die Shareability auf Facebook).

Testen
https://developers.facebook.com/tools/debug/

**Comment by mritzmann** [comment]
Da die Abstimmung über das NDG nicht mehr aktuell ist, schließe ich hiermit alle Issues. Bei bedarf einer Weiterentwicklung kann dieses Issues erneut geöffnet werden.

**Comment by mritzmann** [comment]
Sehe gerade, dass ich OpenGraph tatsächlich eingebaut habe. Dieses Issues ist also somit tatsächlich gelöst.
