### ISSUE TITLE
Zusätzlich GET ermöglichen

### ISSUE THREAD

**Issue by mritzmann** [mritzmann/NDG-Lieblingswebsite#3]
Damit Ergebnis verlinkbar wird.

**Comment by valioDOTch** [comment]
Das würde die Shareability auf jeden Fall erhöhen!

**Comment by mritzmann** [comment]
Da die Abstimmung über das NDG nicht mehr aktuell ist, schließe ich hiermit alle Issues. Bei bedarf einer Weiterentwicklung kann dieses Issues erneut geöffnet werden.
